#!/bin/bash

# clear index
rm -f ./index.js
babel ./src/index.js -o ./index.js

modules=`ls ./src | grep -v js`
length=`echo $modules | wc -w | tr -d '[[:space:]]'`
processed=1

for module in $modules
do
  rm -rf $module && mkdir $module

  echo "[$processed/$length] building module '$module'"
  babel "./src/$module/" --no-comments -qd "./$module/"

  processed=$[processed + 1]
done
