#!/bin/bash
releasy=./node_modules/.bin/releasy
type=$1 #[ major | minor | patch (default) ]
npm run dist
git add . && git commit -am "build dist"
$releasy $type -qsf bower.json --stable --no-tag --no-push
$releasy $type -s --stable
npm publish
